_In this week, we will use basketball data downloaded from NBA.com to demonstrate how to import data into Python, how to clean up data before conducting any data analyses, as well how to describe and summarize data._ 


## Importing data into Python
### Before we import the dataset into Jupyter notebook, we need to first import the Python libraries that we will use to analyze the data
- pandas
- numpy

In [1]:
import pandas as pd
import numpy as np

#### In our data repository, we have a dataset that contains NBA team information. Let's import this dataset into the Jupyter notebook.

In [2]:
NBA_Teams=pd.read_csv("../../Data/Week 2/nba_teams.csv")

We can take a quick look at the data we imported by displaying the dataset.

In [3]:
display(NBA_Teams)

,Unnamed: 0,ABBREVIATION,CITY,FULL_NAME,ID,NICKNAME,STATE,YEAR_FOUNDED
0,0,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949
1,1,BOS,Boston,Boston Celtics,1610612738,Celtics,Massachusetts,1946
2,2,CLE,Cleveland,Cleveland Cavaliers,1610612739,Cavaliers,Ohio,1970
3,3,NOP,New Orleans,New Orleans Pelicans,1610612740,Pelicans,Louisiana,2002
4,4,CHI,Chicago,Chicago Bulls,1610612741,Bulls,Illinois,1966
5,5,DAL,Dallas,Dallas Mavericks,1610612742,Mavericks,Texas,1980
6,6,DEN,Denver,Denver Nuggets,1610612743,Nuggets,Colorado,1976
7,7,GSW,Golden State,Golden State Warriors,1610612744,Warriors,California,1946
8,8,HOU,Houston,Houston Rockets,1610612745,Rockets,Texas,1967
9,9,LAC,Los Angeles,Los Angeles Clippers,1610612746,Clippers,California,1970
10,10,LAL,Los Angeles,Los Angeles Lakers,1610612747,Lakers,California,1948
11,11,MIA,Miami,Miami Heat,1610612748,Heat,Florida,1988
12,12,MIL,Milwaukee,Milwaukee Bucks,1610612749,Bucks,Wisconsin,1968
13,13,MIN,Minnesota,Minnesota Timberwolves,1610612750,Timberwolves,Minnesota,1989
14,14,BKN,Brooklyn,Brooklyn Nets,1610612751,Nets,New York,1976
15,15,NYK,New York,New York Knicks,1610612752,Knicks,New York,1946
16,16,ORL,Orlando,Orlando Magic,1610612753,Magic,Florida,1989
17,17,IND,Indiana,Indiana Pacers,1610612754,Pacers,Indiana,1976
18,18,PHI,Philadelphia,Philadelphia 76ers,1610612755,76ers,Pennsylvania,1949
19,19,PHX,Phoenix,Phoenix Suns,1610612756,Suns,Arizona,1968
20,20,POR,Portland,Portland Trail Blazers,1610612757,Trail Blazers,Oregon,1970
21,21,SAC,Sacramento,Sacramento Kings,1610612758,Kings,California,1948
22,22,SAS,San Antonio,San Antonio Spurs,1610612759,Spurs,Texas,1976
23,23,OKC,Oklahoma City,Oklahoma City Thunder,1610612760,Thunder,Oklahoma,1967
24,24,TOR,Toronto,Toronto Raptors,1610612761,Raptors,Ontario,1995
25,25,UTA,Utah,Utah Jazz,1610612762,Jazz,Utah,1974
26,26,MEM,Memphis,Memphis Grizzlies,1610612763,Grizzlies,Tennessee,1995
27,27,WAS,Washington,Washington Wizards,1610612764,Wizards,District of Columbia,1961
28,28,DET,Detroit,Detroit Pistons,1610612765,Pistons,Michigan,1948
29,29,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988

_This dataset provides some basic information of the NBA teams._ 

For a dataset, each row represents an observation, i.e., a team in this dataset and each column represents a variable which contains information of a characteristics of the observation. A variable can take different values in different situations. The number of observation in a dataset represents the size of our sample and the number of variables represents the richness of information in our dataset. 

#### We can use the “shape” function in Python to see how many variables and observations in our dataset.

In [4]:
NBA_Teams.shape

(30, 8)

_We can see that there are 30 observations (rows) and 8 variables (columns)._

### Renaming Variables
####  We can rename a variable using the “rename” function in Python.
_Inplace parameter_
- True: replace the old variable with a new name; 
- False: create a new variable with the new name.

The first variable is unnamed, let's rename it to be "TEAM_NUMBER"; let's also rename "ID" to "TEAM_ID."

In [7]:
NBA_Teams.rename(columns = {'Unnamed: 0':'TEAM_NUMBER', 'ID':'TEAM_ID'}, inplace = True)
display(NBA_Teams)

,TEAM_NUMBER,ABBREVIATION,CITY,FULL_NAME,TEAM_ID,NICKNAME,STATE,YEAR_FOUNDED
0,0,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949
1,1,BOS,Boston,Boston Celtics,1610612738,Celtics,Massachusetts,1946
2,2,CLE,Cleveland,Cleveland Cavaliers,1610612739,Cavaliers,Ohio,1970
3,3,NOP,New Orleans,New Orleans Pelicans,1610612740,Pelicans,Louisiana,2002
4,4,CHI,Chicago,Chicago Bulls,1610612741,Bulls,Illinois,1966
5,5,DAL,Dallas,Dallas Mavericks,1610612742,Mavericks,Texas,1980
6,6,DEN,Denver,Denver Nuggets,1610612743,Nuggets,Colorado,1976
7,7,GSW,Golden State,Golden State Warriors,1610612744,Warriors,California,1946
8,8,HOU,Houston,Houston Rockets,1610612745,Rockets,Texas,1967
9,9,LAC,Los Angeles,Los Angeles Clippers,1610612746,Clippers,California,1970
10,10,LAL,Los Angeles,Los Angeles Lakers,1610612747,Lakers,California,1948
11,11,MIA,Miami,Miami Heat,1610612748,Heat,Florida,1988
12,12,MIL,Milwaukee,Milwaukee Bucks,1610612749,Bucks,Wisconsin,1968
13,13,MIN,Minnesota,Minnesota Timberwolves,1610612750,Timberwolves,Minnesota,1989
14,14,BKN,Brooklyn,Brooklyn Nets,1610612751,Nets,New York,1976
15,15,NYK,New York,New York Knicks,1610612752,Knicks,New York,1946
16,16,ORL,Orlando,Orlando Magic,1610612753,Magic,Florida,1989
17,17,IND,Indiana,Indiana Pacers,1610612754,Pacers,Indiana,1976
18,18,PHI,Philadelphia,Philadelphia 76ers,1610612755,76ers,Pennsylvania,1949
19,19,PHX,Phoenix,Phoenix Suns,1610612756,Suns,Arizona,1968
20,20,POR,Portland,Portland Trail Blazers,1610612757,Trail Blazers,Oregon,1970
21,21,SAC,Sacramento,Sacramento Kings,1610612758,Kings,California,1948
22,22,SAS,San Antonio,San Antonio Spurs,1610612759,Spurs,Texas,1976
23,23,OKC,Oklahoma City,Oklahoma City Thunder,1610612760,Thunder,Oklahoma,1967
24,24,TOR,Toronto,Toronto Raptors,1610612761,Raptors,Ontario,1995
25,25,UTA,Utah,Utah Jazz,1610612762,Jazz,Utah,1974
26,26,MEM,Memphis,Memphis Grizzlies,1610612763,Grizzlies,Tennessee,1995
27,27,WAS,Washington,Washington Wizards,1610612764,Wizards,District of Columbia,1961
28,28,DET,Detroit,Detroit Pistons,1610612765,Pistons,Michigan,1948
29,29,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988

## Self Test - 1
- Rename "FULL_NAME" to "TEAM_NAME"

In [8]:
#Your Code Here
NBA_Teams.rename(columns = {'FULL_NAME':'TEAM_NAME'}, inplace = True)
NBA_Teams

,TEAM_NUMBER,ABBREVIATION,CITY,TEAM_NAME,TEAM_ID,NICKNAME,STATE,YEAR_FOUNDED
0,0,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949
1,1,BOS,Boston,Boston Celtics,1610612738,Celtics,Massachusetts,1946
2,2,CLE,Cleveland,Cleveland Cavaliers,1610612739,Cavaliers,Ohio,1970
3,3,NOP,New Orleans,New Orleans Pelicans,1610612740,Pelicans,Louisiana,2002
4,4,CHI,Chicago,Chicago Bulls,1610612741,Bulls,Illinois,1966
5,5,DAL,Dallas,Dallas Mavericks,1610612742,Mavericks,Texas,1980
6,6,DEN,Denver,Denver Nuggets,1610612743,Nuggets,Colorado,1976
7,7,GSW,Golden State,Golden State Warriors,1610612744,Warriors,California,1946
8,8,HOU,Houston,Houston Rockets,1610612745,Rockets,Texas,1967
9,9,LAC,Los Angeles,Los Angeles Clippers,1610612746,Clippers,California,1970
10,10,LAL,Los Angeles,Los Angeles Lakers,1610612747,Lakers,California,1948
11,11,MIA,Miami,Miami Heat,1610612748,Heat,Florida,1988
12,12,MIL,Milwaukee,Milwaukee Bucks,1610612749,Bucks,Wisconsin,1968
13,13,MIN,Minnesota,Minnesota Timberwolves,1610612750,Timberwolves,Minnesota,1989
14,14,BKN,Brooklyn,Brooklyn Nets,1610612751,Nets,New York,1976
15,15,NYK,New York,New York Knicks,1610612752,Knicks,New York,1946
16,16,ORL,Orlando,Orlando Magic,1610612753,Magic,Florida,1989
17,17,IND,Indiana,Indiana Pacers,1610612754,Pacers,Indiana,1976
18,18,PHI,Philadelphia,Philadelphia 76ers,1610612755,76ers,Pennsylvania,1949
19,19,PHX,Phoenix,Phoenix Suns,1610612756,Suns,Arizona,1968
20,20,POR,Portland,Portland Trail Blazers,1610612757,Trail Blazers,Oregon,1970
21,21,SAC,Sacramento,Sacramento Kings,1610612758,Kings,California,1948
22,22,SAS,San Antonio,San Antonio Spurs,1610612759,Spurs,Texas,1976
23,23,OKC,Oklahoma City,Oklahoma City Thunder,1610612760,Thunder,Oklahoma,1967
24,24,TOR,Toronto,Toronto Raptors,1610612761,Raptors,Ontario,1995
25,25,UTA,Utah,Utah Jazz,1610612762,Jazz,Utah,1974
26,26,MEM,Memphis,Memphis Grizzlies,1610612763,Grizzlies,Tennessee,1995
27,27,WAS,Washington,Washington Wizards,1610612764,Wizards,District of Columbia,1961
28,28,DET,Detroit,Detroit Pistons,1610612765,Pistons,Michigan,1948
29,29,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988

### Dropping Variables (columns)

#### To drop a variable, i.e., to delete a column, we can use the “drop” command. 
- We need to provide the name of the variable;
- We also need to use the argument “axis=1” which tells Python that we are dropping a column, not a row. 

The variable "TEAM_NUMBER" has little meaning, let's drop it.

In [10]:
NBA_Teams.drop(['TEAM_NUMBER'], axis = 1, inplace = True)
NBA_Teams

,ABBREVIATION,CITY,TEAM_NAME,TEAM_ID,NICKNAME,STATE,YEAR_FOUNDED
0,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949
1,BOS,Boston,Boston Celtics,1610612738,Celtics,Massachusetts,1946
2,CLE,Cleveland,Cleveland Cavaliers,1610612739,Cavaliers,Ohio,1970
3,NOP,New Orleans,New Orleans Pelicans,1610612740,Pelicans,Louisiana,2002
4,CHI,Chicago,Chicago Bulls,1610612741,Bulls,Illinois,1966
5,DAL,Dallas,Dallas Mavericks,1610612742,Mavericks,Texas,1980
6,DEN,Denver,Denver Nuggets,1610612743,Nuggets,Colorado,1976
7,GSW,Golden State,Golden State Warriors,1610612744,Warriors,California,1946
8,HOU,Houston,Houston Rockets,1610612745,Rockets,Texas,1967
9,LAC,Los Angeles,Los Angeles Clippers,1610612746,Clippers,California,1970
10,LAL,Los Angeles,Los Angeles Lakers,1610612747,Lakers,California,1948
11,MIA,Miami,Miami Heat,1610612748,Heat,Florida,1988
12,MIL,Milwaukee,Milwaukee Bucks,1610612749,Bucks,Wisconsin,1968
13,MIN,Minnesota,Minnesota Timberwolves,1610612750,Timberwolves,Minnesota,1989
14,BKN,Brooklyn,Brooklyn Nets,1610612751,Nets,New York,1976
15,NYK,New York,New York Knicks,1610612752,Knicks,New York,1946
16,ORL,Orlando,Orlando Magic,1610612753,Magic,Florida,1989
17,IND,Indiana,Indiana Pacers,1610612754,Pacers,Indiana,1976
18,PHI,Philadelphia,Philadelphia 76ers,1610612755,76ers,Pennsylvania,1949
19,PHX,Phoenix,Phoenix Suns,1610612756,Suns,Arizona,1968
20,POR,Portland,Portland Trail Blazers,1610612757,Trail Blazers,Oregon,1970
21,SAC,Sacramento,Sacramento Kings,1610612758,Kings,California,1948
22,SAS,San Antonio,San Antonio Spurs,1610612759,Spurs,Texas,1976
23,OKC,Oklahoma City,Oklahoma City Thunder,1610612760,Thunder,Oklahoma,1967
24,TOR,Toronto,Toronto Raptors,1610612761,Raptors,Ontario,1995
25,UTA,Utah,Utah Jazz,1610612762,Jazz,Utah,1974
26,MEM,Memphis,Memphis Grizzlies,1610612763,Grizzlies,Tennessee,1995
27,WAS,Washington,Washington Wizards,1610612764,Wizards,District of Columbia,1961
28,DET,Detroit,Detroit Pistons,1610612765,Pistons,Michigan,1948
29,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988

#### Next we will work on game level data.

Import the game level dataset from our data repository. 
- We can display just first five rows of the dataset using the "head" command.

In [11]:
Games=pd.read_csv("../../Data/Week 2/basketball_games.csv")
Games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22019,1611661322,WAS,Washington Mystics,1021900079,8/5/2019,WAS @ LVA,NaN,101,51,...,0.750,3,10,13,14,2,4,5,7,12.2
1,22019,1611661319,LVA,Las Vegas Aces,1021900079,8/5/2019,LVA vs. WAS,NaN,100,36,...,0.800,5,10,15,12,2,0,7,8,-11.8
2,22019,1611661320,LAS,Los Angeles Sparks,1021900124,8/1/2019,LAS vs. LVA,W,200,76,...,1.000,5,28,33,19,7,7,12,18,8.0
3,22019,1611661323,CON,Connecticut Sun,1021900122,8/1/2019,CON vs. PHO,W,200,68,...,0.786,12,28,40,18,13,0,16,15,6.0
4,22019,1611661317,PHO,Phoenix Mercury,1021900122,8/1/2019,PHO @ CON,L,199,62,...,0.778,6,23,29,15,8,9,18,11,-6.0

_Upon importing the game data, we notice that the first five games are not NBA games, instead, they are WNBA games. Indeed, this dataset contains NBA games, WNBA games, NBA 2K (simulation video) games._ 

### Dropping observations (rows)

#### To drop an observation, we can use the index number on the left to specify the row we want to drop.
- The argument axis=0 specifies that we want to drop a row instead of a column.

In [12]:
Games.drop([0], axis=0, inplace=True)
Games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
1,22019,1611661319,LVA,Las Vegas Aces,1021900079,8/5/2019,LVA vs. WAS,NaN,100,36,...,0.800,5,10,15,12,2,0,7,8,-11.8
2,22019,1611661320,LAS,Los Angeles Sparks,1021900124,8/1/2019,LAS vs. LVA,W,200,76,...,1.000,5,28,33,19,7,7,12,18,8.0
3,22019,1611661323,CON,Connecticut Sun,1021900122,8/1/2019,CON vs. PHO,W,200,68,...,0.786,12,28,40,18,13,0,16,15,6.0
4,22019,1611661317,PHO,Phoenix Mercury,1021900122,8/1/2019,PHO @ CON,L,199,62,...,0.778,6,23,29,15,8,9,18,11,-6.0
5,22019,1611661319,LVA,Las Vegas Aces,1021900124,8/1/2019,LVA @ LAS,L,200,68,...,0.765,10,29,39,17,7,4,14,13,-8.0

#### More often, we will drop observations based on certain conditions. 

For example, Las Vegas Aces is a women’s basketball team. If we are only going to focus on men’s basketball games, we will drop all the games played by Las Vegas Aces. In this case, we don’t have to use the “drop” function. We can specify our TEAM_NAME variables to be not equal to “Las Vegas Aces.”

In [13]:
Games = Games[Games.TEAM_NAME != 'Las Vegas Aces']
Games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
2,22019,1611661320,LAS,Los Angeles Sparks,1021900124,8/1/2019,LAS vs. LVA,W,200,76,...,1.000,5,28,33,19,7,7,12,18,8.0
3,22019,1611661323,CON,Connecticut Sun,1021900122,8/1/2019,CON vs. PHO,W,200,68,...,0.786,12,28,40,18,13,0,16,15,6.0
4,22019,1611661317,PHO,Phoenix Mercury,1021900122,8/1/2019,PHO @ CON,L,199,62,...,0.778,6,23,29,15,8,9,18,11,-6.0
6,22019,1611661313,NYL,New York Liberty,1021900123,8/1/2019,NYL @ DAL,L,200,64,...,0.800,6,21,27,15,10,2,21,26,-23.0
7,22019,1611661321,DAL,Dallas Wings,1021900123,8/1/2019,DAL vs. NYL,W,200,87,...,0.833,9,24,33,24,13,6,18,21,23.0

## Self Test - 2
- Drop all the Phoenix Mercury games

In [14]:
#Your Code Here
Games = Games[Games.TEAM_NAME != 'Phoenix Mercury']
Games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
2,22019,1611661320,LAS,Los Angeles Sparks,1021900124,8/1/2019,LAS vs. LVA,W,200,76,...,1.000,5,28,33,19,7,7,12,18,8.0
3,22019,1611661323,CON,Connecticut Sun,1021900122,8/1/2019,CON vs. PHO,W,200,68,...,0.786,12,28,40,18,13,0,16,15,6.0
6,22019,1611661313,NYL,New York Liberty,1021900123,8/1/2019,NYL @ DAL,L,200,64,...,0.800,6,21,27,15,10,2,21,26,-23.0
7,22019,1611661321,DAL,Dallas Wings,1021900123,8/1/2019,DAL vs. NYL,W,200,87,...,0.833,9,24,33,24,13,6,18,21,23.0
8,22019,1611661325,IND,Indiana Fever,1021900121,7/31/2019,IND vs. ATL,W,200,61,...,0.731,7,36,43,14,11,4,15,17,2.0
9,22019,1611661330,ATL,Atlanta Dream,1021900121,7/31/2019,ATL @ IND,L,201,59,...,0.667,12,32,44,17,7,5,15,21,-2.0
11,22019,1611661322,WAS,Washington Mystics,1021900119,7/30/2019,WAS vs. PHO,W,200,99,...,0.800,10,23,33,21,6,4,8,13,6.0
12,22019,1611661323,CON,Connecticut Sun,1021900118,7/30/2019,CON vs. CHI,W,201,100,...,0.762,10,27,37,29,6,4,16,22,6.0
13,22019,1611661321,DAL,Dallas Wings,1021900120,7/30/2019,DAL @ LVA,L,201,54,...,0.600,10,29,39,11,4,4,18,22,-32.0
14,22019,1611661329,CHI,Chicago Sky,1021900118,7/30/2019,CHI @ CON,L,200,94,...,0.783,8,23,31,26,6,3,14,20,-6.0
16,32019,1611665409,EDD,Team Delle Donne,1031900001,7/27/2019,EDD @ WIL,L,199,126,...,1.000,15,39,54,38,4,2,11,1,-3.0
17,32019,1611665410,WIL,Team Wilson,1031900001,7/27/2019,WIL vs. EDD,W,201,129,...,NaN,16,31,47,31,9,0,7,4,3.0
18,42019,200,SGC,76ers GC,1241900211,7/26/2019,SGC vs. CCG,W,120,55,...,0.000,6,8,14,18,7,2,10,9,4.0
19,42019,205,CCG,Celtics Crossover Gaming,1241900211,7/26/2019,CCG @ SGC,L,120,51,...,1.000,6,8,14,14,8,0,9,6,-4.0
20,42019,227,TWG,T-Wolves Gaming,1241900201,7/26/2019,TWG vs. WGS,W,120,71,...,0.750,10,13,23,21,6,4,4,11,18.0
21,42019,227,TWG,T-Wolves Gaming,1241900202,7/26/2019,TWG @ WGS,W,120,68,...,1.000,7,7,14,19,16,3,13,7,22.0
22,42019,229,WGS,Warriors Gaming Squad,1241900201,7/26/2019,WGS @ TWG,L,120,53,...,0.667,5,12,17,15,3,3,8,11,-18.0
23,42019,205,CCG,Celtics Crossover Gaming,1241900212,7/26/2019,CCG vs. SGC,L,120,59,...,0.667,5,7,12,20,4,0,16,14,-37.0
24,42019,229,WGS,Warriors Gaming Squad,1241900202,7/26/2019,WGS vs. TWG,L,120,46,...,0.667,9,4,13,15,9,0,23,8,-22.0
25,42019,200,SGC,76ers GC,1241900212,7/26/2019,SGC @ CCG,W,120,96,...,0.813,6,8,14,23,12,3,5,12,37.0
26,42019,200,SGC,76ers GC,1241900121,7/25/2019,SGC vs. PCG,W,120,55,...,1.000,7,13,20,18,6,3,9,7,5.0
27,42019,227,TWG,T-Wolves Gaming,1241900132,7/25/2019,TWG @ KGG,W,120,56,...,0.571,4,13,17,12,9,5,5,9,7.0
28,42019,200,SGC,76ers GC,1241900122,7/25/2019,SGC @ PCG,W,120,69,...,0.500,6,11,17,18,10,2,5,9,14.0
29,42019,213,KGG,Kings Guard Gaming,1241900131,7/25/2019,KGG @ TWG,L,120,51,...,1.000,1,9,10,15,4,4,9,12,-13.0
30,42019,213,KGG,Kings Guard Gaming,1241900132,7/25/2019,KGG vs. TWG,L,120,49,...,0.750,6,11,17,17,3,3,12,9,-7.0
31,42019,220,PCG,Pacers Gaming,1241900121,7/25/2019,PCG @ SGC,L,120,50,...,1.000,3,8,11,14,8,0,8,12,-5.0
32,42019,220,PCG,Pacers Gaming,1241900122,7/25/2019,PCG vs. SGC,L,120,55,...,0.500,5,12,17,18,4,3,13,8,-14.0
33,42019,227,TWG,T-Wolves Gaming,1241900131,7/25/2019,TWG vs. KGG,W,120,64,...,0.833,4,10,14,17,6,5,4,7,13.0
34,42019,205,CCG,Celtics Crossover Gaming,1241900111,7/24/2019,CCG @ MVG,W,120,63,...,1.000,9,10,19,14,11,2,9,9,8.0
35,22019,1611661323,CON,Connecticut Sun,1021900116,7/24/2019,CON vs. NYL,W,200,70,...,0.588,13,31,44,19,8,2,11,18,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29970,22012,1610612756,PHX,Phoenix Suns,21200932,3/9/2013,PHX vs. HOU,W,239,107,...,0.641,17,30,47,18,13,4,16,20,2.0
29971,22012,1610612752,NYK,New York Knicks,21200928,3/9/2013,NYK vs. UTA,W,239,113,...,0.800,8,31,39,21,11,3,12,19,29.0
29972,22012,1610612740,NOH,New Orleans Hornets,21200930,3/9/2013,NOH @ MEM,L,241,85,...,0.882,11,31,42,17,4,1,12,19,-11.0
29973,22012,1610612763,MEM,Memphis Grizzlies,21200930,3/9/2013,MEM vs. NOH,W,241,96,...,0.800,14,29,43,21,7,11,10,16,11.0
29974,22012,1610612743,DEN,Denver Nuggets,21200931,3/9/2013,DEN vs. MIN,W,239,111,...,0.818,6,37,43,23,13,8,19,21,23.0
29975,22012,1610612749,MIL,Milwaukee Bucks,21200933,3/9/2013,MIL @ GSW,W,238,103,...,0.737,6,36,42,29,8,5,15,20,10.0
29976,22012,1610612744,GSW,Golden State Warriors,21200933,3/9/2013,GSW vs. MIL,L,241,93,...,0.650,12,35,47,21,4,1,17,21,-10.0
29977,22012,1612709913,ERI,Erie BayHawks,2021200287,3/9/2013,ERI vs. BAK,W,242,118,...,0.815,7,28,35,22,13,2,11,23,20.2
29978,22012,1610612750,MIN,Minnesota Timberwolves,21200931,3/9/2013,MIN @ DEN,L,240,88,...,0.684,10,30,40,23,5,7,22,21,-23.0
29979,22012,1610612766,CHA,Charlotte Bobcats,21200929,3/9/2013,CHA @ WAS,L,241,87,...,0.783,7,25,32,19,8,2,12,21,-17.0
29980,22012,1612709900,BAK,Bakersfield Jam,2021200287,3/9/2013,BAK @ ERI,L,239,97,...,0.714,16,33,49,16,5,2,23,22,-21.0
29981,22012,1610612751,BKN,Brooklyn Nets,21200927,3/9/2013,BKN @ ATL,W,242,93,...,0.682,9,34,43,20,12,6,9,15,13.0
29982,22012,1610612745,HOU,Houston Rockets,21200932,3/9/2013,HOU @ PHX,L,240,105,...,0.667,15,24,39,22,10,5,19,24,-2.0
29983,22012,1612709903,IDA,Idaho Stampede,2021200290,3/9/2013,IDA @ SCW,L,240,88,...,0.600,13,26,39,21,15,3,10,22,-14.0
29984,22012,1612709902,SCW,Santa Cruz Warriors,2021200290,3/9/2013,SCW vs. IDA,W,240,101,...,0.655,11,43,54,29,7,13,22,19,13.0
29985,22012,1610612764,WAS,Washington Wizards,21200929,3/9/2013,WAS vs. CHA,W,241,104,...,0.750,9,36,45,23,6,5,16,26,17.0
29986,22012,1612709914,RNO,Reno Bighorns,2021200289,3/9/2013,RNO vs. SXF,L,240,110,...,0.806,3,25,28,25,11,4,19,22,-3.0
29987,22012,1610612737,ATL,Atlanta Hawks,21200927,3/9/2013,ATL vs. BKN,L,240,80,...,0.688,13,31,44,20,3,2,17,20,-13.0
29988,22012,1612709890,AUS,Austin Toros,2021200288,3/9/2013,AUS @ LAD,L,241,91,...,0.667,22,34,56,22,9,7,20,24,-4.0
29989,22012,1612709904,SXF,Sioux Falls Skyforce,2021200289,3/9/2013,SXF @ RNO,W,241,113,...,0.769,15,32,47,15,13,4,25,28,3.0
29990,22012,1610612762,UTA,Utah Jazz,21200928,3/9/2013,UTA @ NYK,L,240,84,...,0.762,11,29,40,13,4,2,19,23,-29.0
29991,22012,1612709905,LAD,Los Angeles D-Fenders,2021200288,3/9/2013,LAD vs. AUS,W,241,95,...,0.686,10,28,38,16,12,6,10,14,4.0
29992,22012,1610612764,WAS,Washington Wizards,21200918,3/8/2013,WAS @ BKN,L,239,78,...,0.647,14,30,44,18,10,8,11,28,-17.0
29993,22012,1610612761,TOR,Toronto Raptors,21200925,3/8/2013,TOR @ LAL,L,265,116,...,0.750,7,36,43,32,8,6,17,27,-2.0
29994,22012,1610612745,HOU,Houston Rockets,21200926,3/8/2013,HOU @ GSW,W,239,94,...,0.735,7,38,45,21,11,2,12,17,6.0
29995,22012,1612709902,SCW,Santa Cruz Warriors,2021200286,3/8/2013,SCW vs. SXF,W,241,86,...,0.727,13,45,58,24,11,9,21,20,22.0
29996,22012,1610612741,CHI,Chicago Bulls,21200922,3/8/2013,CHI vs. UTA,W,241,89,...,0.833,21,29,50,19,8,1,11,16,1.0
29997,22012,1610612753,ORL,Orlando Magic,21200916,3/8/2013,ORL vs. IND,L,239,86,...,0.895,12,26,38,16,8,5,20,22,-29.0
29998,22012,1610612756,PHX,Phoenix Suns,21200924,3/8/2013,PHX @ SAC,L,240,112,...,0.826,12,26,38,33,9,6,13,17,-9.0
29999,22012,1610612737,ATL,Atlanta Hawks,21200917,3/8/2013,ATL @ BOS,L,264,102,...,0.765,10,31,41,32,7,3,14,17,-5.0

## Merging Dataframes

#### We will only focus on NBA games. We could merge the NBA_Teams and Games datasets to filter out NBA games.

#### Teams are identified by the TEAM_ID. So, let’s merge the datasets by TEAM_ID. Since the variable “TEAM_NAME” is also present in both datasets, we could also include this variable as a criteria to merge the datasets so that in our new dataset, there is no duplicate variables.

In [15]:
NBA_Games = pd.merge(NBA_Teams, Games, on = ['TEAM_ID', 'TEAM_NAME'])
NBA_Games

,ABBREVIATION,CITY,TEAM_NAME,TEAM_ID,NICKNAME,STATE,YEAR_FOUNDED,SEASON_ID,TEAM_ABBREVIATION,GAME_ID,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22019,ATL,1521900072,...,0.850,13,23,36,14,15,3,12,24,8.0
1,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22019,ATL,1521900060,...,0.700,9,28,37,19,10,8,22,25,-5.0
2,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22019,ATL,1521900042,...,0.708,7,27,34,17,5,5,18,21,18.2
3,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22019,ATL,1521900023,...,0.500,1,2,3,1,0,1,4,2,0.0
4,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22019,ATL,1521900023,...,0.625,9,27,36,7,7,10,18,28,-24.0
5,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22019,ATL,1521900013,...,0.885,9,30,39,13,11,6,13,21,2.0
6,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21801220,...,0.816,22,39,61,29,5,7,17,25,-1.0
7,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21801202,...,0.526,9,39,48,25,2,3,11,28,-8.0
8,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21801181,...,0.677,10,28,38,21,16,4,14,21,-36.0
9,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21801168,...,0.786,11,33,44,29,7,7,11,26,8.0
10,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21801162,...,0.650,11,32,43,26,13,2,11,18,-6.0
11,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21801145,...,0.588,15,43,58,36,10,10,9,13,1.0
12,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21801131,...,0.929,8,33,41,20,5,7,10,22,-20.0
13,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21801113,...,0.885,9,32,41,30,13,4,16,26,10.0
14,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21801088,...,0.762,15,34,49,28,8,7,12,25,2.0
15,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21801076,...,0.696,9,34,43,26,8,5,16,23,3.0
16,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21801060,...,0.800,8,37,45,30,6,1,19,23,-16.0
17,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21801046,...,0.700,8,42,50,20,8,3,18,29,-10.0
18,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21801034,...,0.792,19,31,50,27,11,5,17,25,-9.0
19,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21801016,...,0.786,15,36,51,35,9,9,11,26,21.0
20,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21800995,...,0.833,10,46,56,30,4,5,9,12,12.0
21,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21800987,...,0.813,18,39,57,22,7,2,10,37,-2.0
22,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21800968,...,0.792,11,36,47,21,8,2,14,18,-7.0
23,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21800953,...,0.800,16,26,42,25,9,2,14,21,-1.0
24,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21800946,...,0.643,11,35,46,30,10,5,13,18,5.0
25,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21800928,...,0.680,9,50,59,33,11,8,20,34,-7.0
26,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21800912,...,0.844,18,47,65,32,1,6,12,25,8.0
27,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21800903,...,0.696,10,31,41,21,6,6,17,24,-8.0
28,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21800883,...,0.842,12,38,50,22,8,9,13,22,8.0
29,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,21800877,...,0.842,10,37,47,21,6,4,18,24,-3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18391,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,21400198,...,0.800,5,28,33,21,6,4,5,17,-21.0
18392,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,21400195,...,0.750,5,28,33,18,9,1,11,19,-1.0
18393,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,21400172,...,0.600,10,35,45,22,4,7,7,26,-5.0
18394,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,21400160,...,0.583,12,29,41,18,6,6,5,21,-2.0
18395,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,21400146,...,0.462,7,28,35,22,1,3,11,17,-27.0
18396,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,21400140,...,0.571,10,31,41,14,5,2,12,13,-25.0
18397,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,21400130,...,0.947,14,32,46,21,5,3,7,15,8.0
18398,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,21400107,...,0.852,6,32,38,16,5,3,13,16,-2.0
18399,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,21400097,...,0.704,12,27,39,15,5,0,11,18,-15.0
18400,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,21400071,...,0.741,11,40,51,31,6,7,19,30,3.0
18401,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,21400057,...,0.724,13,36,49,23,4,9,12,24,7.0
18402,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,21400054,...,0.846,6,28,34,23,6,1,12,15,-9.0
18403,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,21400041,...,0.724,8,30,38,20,7,2,12,16,-3.0
18404,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,21400028,...,0.722,5,39,44,17,10,4,20,16,-2.0
18405,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,21400004,...,0.690,15,35,50,27,8,9,10,20,2.0
18406,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,12014,CHA,11400107,...,0.808,3,31,34,18,8,9,10,22,-9.0
18407,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,12014,CHA,11400089,...,0.828,13,39,52,31,9,7,18,35,-3.0
18408,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,12014,CHA,11400083,...,0.750,10,36,46,25,4,3,13,20,-5.0
18409,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,12014,CHA,11400065,...,1.000,8,33,41,25,13,2,17,25,10.0
18410,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,12014,CHA,11400053,...,0.862,8,28,36,15,4,8,6,20,-20.0
18411,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,12014,CHA,11400043,...,0.800,13,34,47,24,5,7,13,23,2.0
18412,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,12014,CHA,11400027,...,0.696,9,37,46,26,4,4,10,22,13.0
18413,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,12014,CHA,11400016,...,0.656,11,39,50,15,6,4,14,30,-14.0
18414,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,1521400065,...,0.750,16,34,50,10,6,8,13,24,-4.0
18415,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,1521400061,...,0.846,12,24,36,17,6,6,11,24,3.0
18416,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,1521400046,...,0.762,12,26,38,19,7,2,11,22,29.0
18417,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,1521400038,...,0.667,7,33,40,10,7,2,21,31,1.0
18418,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,1521400023,...,0.618,4,19,23,10,5,5,16,19,-23.0
18419,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,1521400017,...,0.615,19,28,47,9,5,1,17,39,-7.0
18420,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988,22014,CHA,1521400004,...,0.789,14,20,34,4,8,8,14,20,-12.0

### Understanding and cleaning the merged dataset

_As you can tell, the merged dataset has a lot more variables and Python cannot fit all of them in the screen._ 

#### We can obtain the list of variables using the “columns” command. This provides us a full list of variables in our dataset.

In [16]:
NBA_Games.columns

Index(['ABBREVIATION', 'CITY', 'TEAM_NAME', 'TEAM_ID', 'NICKNAME', 'STATE',
       'YEAR_FOUNDED', 'SEASON_ID', 'TEAM_ABBREVIATION', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'PTS', 'FGM', 'FGA', 'FG_PCT',
       'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB',
       'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PLUS_MINUS'],
      dtype='object')

#### Data Cleaning
The variable “ABBREVIATION” AND “TEAM_ABBREVIATION” carry the same information and it is not necessary to keep both of them. 
- Delete "ABBREVIATION"

In [17]:
NBA_Games.drop(['ABBREVIATION'], axis = 1, inplace = True, errors = 'ignore')

## Self Test - 3
- Find the number of observations and the number of variables in the dataset

In [18]:
#Your Code Here
NBA_Games.shape

(18421, 32)

The merged dataset is sorted by the criteria we use to merge the datasets. Thus, the NBA_Games dataset is currently sorted by "TEAM_ID." We may be interested to sort the data by other criteria, for example, the date of the game. 

#### We can do so by using the “sort_values” option. 

In our dataset, "GAME_ID" is created based on the date of the game. We can sort the games by “GAME_ID” and display the 20 most recent games.

In [19]:
NBA_Games.sort_values(by=['GAME_ID'], ascending=[False]).head(20)

,CITY,TEAM_NAME,TEAM_ID,NICKNAME,STATE,YEAR_FOUNDED,SEASON_ID,TEAM_ABBREVIATION,GAME_ID,GAME_DATE,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
13449,San Antonio,San Antonio Spurs,1610612759,Spurs,Texas,1976,22019,SAS,1621900006,7/3/2019,...,0.615,9,29,38,12,5,3,11,14,-7.2
15445,Utah,Utah Jazz,1610612762,Jazz,Utah,1974,22019,UTA,1621900006,7/3/2019,...,0.684,13,31,44,15,6,5,15,25,5.8
1304,Cleveland,Cleveland Cavaliers,1610612739,Cavaliers,Ohio,1970,22019,CLE,1621900005,7/3/2019,...,0.737,3,26,29,15,9,3,17,12,-13.0
16076,Memphis,Memphis Grizzlies,1610612763,Grizzlies,Tennessee,1995,22019,MEM,1621900005,7/3/2019,...,0.692,11,36,47,19,8,5,14,19,13.0
15446,Utah,Utah Jazz,1610612762,Jazz,Utah,1974,22019,UTA,1621900004,7/2/2019,...,0.750,11,34,45,18,3,4,14,18,14.6
1305,Cleveland,Cleveland Cavaliers,1610612739,Cavaliers,Ohio,1970,22019,CLE,1621900004,7/2/2019,...,0.682,6,27,33,13,6,0,6,14,-15.0
13450,San Antonio,San Antonio Spurs,1610612759,Spurs,Texas,1976,22019,SAS,1621900003,7/2/2019,...,0.870,10,35,45,24,10,7,18,24,16.6
16077,Memphis,Memphis Grizzlies,1610612763,Grizzlies,Tennessee,1995,22019,MEM,1621900003,7/2/2019,...,0.867,10,29,39,17,6,5,17,18,-15.8
15447,Utah,Utah Jazz,1610612762,Jazz,Utah,1974,22019,UTA,1621900002,7/1/2019,...,0.462,14,27,41,16,10,7,19,26,-6.6
16078,Memphis,Memphis Grizzlies,1610612763,Grizzlies,Tennessee,1995,22019,MEM,1621900002,7/1/2019,...,0.704,8,32,40,14,14,4,20,19,7.4
1306,Cleveland,Cleveland Cavaliers,1610612739,Cavaliers,Ohio,1970,22019,CLE,1621900001,7/1/2019,...,0.667,14,17,31,22,11,3,14,26,-8.0
13451,San Antonio,San Antonio Spurs,1610612759,Spurs,Texas,1976,22019,SAS,1621900001,7/1/2019,...,0.706,5,26,31,18,8,2,22,15,7.0
15545,Utah,Utah Jazz,1610612762,Jazz,Utah,1974,22018,UTA,1621800006,7/5/2018,...,0.633,8,36,44,21,11,7,19,25,-1.4
99,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,1621800006,7/5/2018,...,0.654,15,33,48,16,11,5,17,25,2.2
16173,Memphis,Memphis Grizzlies,1610612763,Grizzlies,Tennessee,1995,22018,MEM,1621800005,7/5/2018,...,0.706,6,26,32,16,7,6,11,24,-3.2
13551,San Antonio,San Antonio Spurs,1610612759,Spurs,Texas,1976,22018,SAS,1621800005,7/5/2018,...,0.682,6,29,35,20,6,2,14,13,3.2
15546,Utah,Utah Jazz,1610612762,Jazz,Utah,1974,22018,UTA,1621800004,7/3/2018,...,0.773,8,35,43,19,4,3,15,23,-7.0
16174,Memphis,Memphis Grizzlies,1610612763,Grizzlies,Tennessee,1995,22018,MEM,1621800004,7/3/2018,...,0.733,9,27,36,18,5,4,5,17,8.4
13552,San Antonio,San Antonio Spurs,1610612759,Spurs,Texas,1976,22018,SAS,1621800003,7/3/2018,...,0.786,6,45,51,24,9,10,17,23,25.8
100,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949,22018,ATL,1621800003,7/3/2018,...,0.545,14,29,43,12,9,2,12,25,-26.2

## Missing Values

### Before we move on to doing any data analyses, we usually need to check if there is any missing value, that is, the source may have failed to collect some information. 

#### We can use the info() command which will return the total number of observations that have real values. By looking at these total numbers, we can see if there is any variable with missing value.

In [20]:
NBA_Games.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18421 entries, 0 to 18420
Data columns (total 32 columns):
CITY                 18421 non-null object
TEAM_NAME            18421 non-null object
TEAM_ID              18421 non-null int64
NICKNAME             18421 non-null object
STATE                18421 non-null object
YEAR_FOUNDED         18421 non-null int64
SEASON_ID            18421 non-null int64
TEAM_ABBREVIATION    18421 non-null object
GAME_ID              18421 non-null int64
GAME_DATE            18421 non-null object
MATCHUP              18421 non-null object
WL                   18414 non-null object
MIN                  18421 non-null int64
PTS                  18421 non-null int64
FGM                  18421 non-null int64
FGA                  18421 non-null int64
FG_PCT               18419 non-null float64
FG3M                 18421 non-null int64
FG3A                 18421 non-null int64
FG3_PCT              18418 non-null float64
FTM                  18421 non-null int64
FTA                  18421 non-null int64
FT_PCT               18418 non-null float64
OREB                 18421 non-null int64
DREB                 18421 non-null int64
REB                  18421 non-null int64
AST                  18421 non-null int64
STL                  18421 non-null int64
BLK                  18421 non-null int64
TOV                  18421 non-null int64
PF                   18421 non-null int64
PLUS_MINUS           18421 non-null float64
dtypes: float64(4), int64(20), object(8)
memory usage: 4.6+ MB

_The total number of rows is 18421, so there are missing values in variable WL, FG_PCT, FG3_PCT, and FT_PCT._

#### Detecting missing values
We can use the isnull() function and the notnull() function to detect where the missing values are.

In [21]:
NBA_Games.notnull()

,CITY,TEAM_NAME,TEAM_ID,NICKNAME,STATE,YEAR_FOUNDED,SEASON_ID,TEAM_ABBREVIATION,GAME_ID,GAME_DATE,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
12,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
13,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
15,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
17,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
20,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
21,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
22,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
23,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
24,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
25,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
26,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
27,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
28,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
29,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18391,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18392,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18393,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18394,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18395,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18396,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18397,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18398,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18399,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18400,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18401,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18402,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18403,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18404,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18405,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18406,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18407,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18408,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18409,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18410,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18411,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18412,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18413,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18414,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18415,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18416,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18417,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18418,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18419,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18420,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

### Handling Missing Values

There are two main approaches to handle missing values. 
- First, we can simply drop the observations with missing value.

#### Drop observations with missing value in the variable "FG_PCT"

In [22]:
NBA_Games=NBA_Games[pd.notnull(NBA_Games["FG_PCT"])]
NBA_Games.shape

(18419, 32)

- Second, we can replace the missing values with valid values (Imputation), such as mean and median.

#### We can use the fillna() command to replace missing values with the mean or the median of the variable.

In [23]:
NBA_Games=NBA_Games.fillna(NBA_Games.mean())
NBA_Games.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18419 entries, 0 to 18420
Data columns (total 32 columns):
CITY                 18419 non-null object
TEAM_NAME            18419 non-null object
TEAM_ID              18419 non-null int64
NICKNAME             18419 non-null object
STATE                18419 non-null object
YEAR_FOUNDED         18419 non-null int64
SEASON_ID            18419 non-null int64
TEAM_ABBREVIATION    18419 non-null object
GAME_ID              18419 non-null int64
GAME_DATE            18419 non-null object
MATCHUP              18419 non-null object
WL                   18414 non-null object
MIN                  18419 non-null int64
PTS                  18419 non-null int64
FGM                  18419 non-null int64
FGA                  18419 non-null int64
FG_PCT               18419 non-null float64
FG3M                 18419 non-null int64
FG3A                 18419 non-null int64
FG3_PCT              18419 non-null float64
FTM                  18419 non-null int64
FTA                  18419 non-null int64
FT_PCT               18419 non-null float64
OREB                 18419 non-null int64
DREB                 18419 non-null int64
REB                  18419 non-null int64
AST                  18419 non-null int64
STL                  18419 non-null int64
BLK                  18419 non-null int64
TOV                  18419 non-null int64
PF                   18419 non-null int64
PLUS_MINUS           18419 non-null float64
dtypes: float64(4), int64(20), object(8)
memory usage: 4.6+ MB

## Creating variables
We can create a variable equals to the total number of goals made.

In [24]:
NBA_Games['GM']=NBA_Games['FGM']+NBA_Games['FG3M']+NBA_Games['FTM']

## Self Test - 4
- Create a variable called "GA" equals to the total number of goals attempted.

In [27]:
Games.columns

Index(['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'PTS', 'FGM', 'FGA', 'FG_PCT',
       'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB',
       'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PLUS_MINUS'],
      dtype='object')

In [28]:
#Your Code Here
NBA_Games['GA'] = NBA_Games['FTA'] + NBA_Games['FG3A'] + NBA_Games['FGA']

### Create variables based on conditions
- We can create a variable conditional on the value of another variable.

For example, we can create a variable "RESULT" that equals to 1 if the team won the game and 0 otherwise. The result of the game can be captured in the points of the team receive, whether it was positive or negative.

In [29]:
NBA_Games['RESULT'] = np.where(NBA_Games['PLUS_MINUS']>0, 'W', 'L')

We will now drop this newly created "RESULT" variable.

In [30]:
NBA_Games.drop(['RESULT'], axis=1, inplace=True)

### Create a variable within group
In the dataset, each game has two observations, one represents the statistics of the home team, one represents those of the away team. Both observations have the same GAME_ID. We can create a variable "POINT_DIFF" that equals the difference between the points earned by the two teams.

We will first sort the data not only by the "GAME_ID" but also by the result "WL".

In [31]:
NBA_Games.sort_values(['GAME_ID','WL'], inplace=True)
NBA_Games["POINT_DIFF"]=NBA_Games.groupby(["GAME_ID"])["PTS"].diff()

The "POINT_DIFF" variable only has the point difference for the winning team, we need to impute the point difference for the losing team as well.

In [32]:
NBA_Games['POINT_DIFF'] = NBA_Games['POINT_DIFF'].fillna(NBA_Games.groupby('GAME_ID')['POINT_DIFF'].transform('mean'))

- We can also drop all observations with missing value in at least one variable using the "dropna()" command.

In [33]:
NBA_Games=NBA_Games.dropna()
NBA_Games.shape

(17779, 35)

### Creating new dataframe

#### Create a new dataframe that aggregates information by group

Sometimes we may want to work with season level data rather than team level data. We can create a new dataset that includes aggregate information of team statistics in each season.

In [34]:
NBA_Team_Stats=NBA_Games.groupby(['TEAM_ID', 'SEASON_ID'])['PTS','FGM','FGA','FG_PCT','FG3M','FG3A','FG3_PCT','FTM','FTA','FT_PCT','OREB','DREB','REB','AST','STL','BLK','TOV','PF','PLUS_MINUS'].sum()
display(NBA_Team_Stats)

                       PTS   FGM   FGA  FG_PCT  FG3M  FG3A  FG3_PCT   FTM  \
TEAM_ID    SEASON_ID
1610612737 12013       523   193   459   2.520    34   131    1.576   103
           12014       708   247   554   3.122    66   182    2.549   148
           12015       652   226   548   2.896    59   176    2.340   141
           12016       686   261   593   3.083    50   159    2.140   114
           12017       480   167   410   2.045    51   156    1.611    95
           12018       563   206   445   2.312    63   189    1.659    88
           22012      2074   795  1701   9.824   155   454    7.206   329
           22013      8272  3061  6719  37.846   747  2085   29.419  1403
           22014      8786  3253  7017  40.399   848  2256   32.719  1432
           22015      8701  3265  7163  39.250   833  2403   29.818  1338
           22016      8736  3219  7142  38.784   760  2214   29.491  1538
           22017      8683  3206  7208  37.909   919  2567   30.388  1352
           22018      9742  3555  7987  39.210  1121  3226   30.483  1511
           22019       381   127   342   1.873    43   136    1.571    84
           42012       536   196   464   2.533    37   112    1.900   107
           42013       647   212   551   2.729    79   230    2.483   144
           42014      1568   590  1369   6.907   145   458    5.030   243
           42015      1001   366   848   4.337   106   318    3.332   163
           42016       633   225   507   2.662    50   164    1.798   133
1610612738 12013       754   276   654   3.404    54   186    2.313   148
           12014       788   278   652   3.415    82   230    2.866   150
           12015       495   187   438   2.154    44   121    1.828    77
           12016       735   271   595   3.210    71   207    2.409   122
           12017       425   155   361   1.724    50   124    1.613    65
           12018       409   148   370   1.608    34   138    1.012    79
           22012      1679   639  1327   8.192   119   316    6.483   282
           22013      8044  3050  6991  36.818   580  1772   27.093  1364
           22014      8728  3335  7580  38.363   701  2173   28.094  1357
           22015      9124  3357  7697  38.360   762  2292   29.406  1648
           22016      9319  3315  7330  39.823  1022  2844   31.486  1667
...                    ...   ...   ...     ...   ...   ...      ...   ...
1610612764 42016      1405   521  1139   5.959   109   344    4.170   254
           42017       643   238   511   2.793    48   131    2.239   119
1610612765 12013       655   228   522   3.068    51   141    2.492   148
           12014       698   249   570   3.067    59   171    2.399   141
           12015       824   302   667   3.641    78   212    2.940   142
           12016       565   216   485   2.680    40   129    1.804    93
           12017       517   202   437   2.311    43   119    1.796    70
           12018       524   190   467   2.042    67   204    1.628    77
           22012      1534   585  1256   7.487    95   297    5.077   269
           22013      8363  3194  7181  37.350   513  1625   25.813  1462
           22014      8514  3187  7358  37.791   746  2163   29.631  1394
           22015      8393  3121  7117  36.482   743  2150   28.588  1408
           22016      8351  3270  7298  37.161   638  1948   26.954  1173
           22017      8754  3298  7310  38.371   913  2438   31.727  1245
           22018      9020  3271  7500  37.520  1004  2946   29.104  1474
           22019       376   131   311   1.703    48   134    1.449    66
           42015       380   144   301   1.916    35    93    1.430    57
           42018       392   150   387   1.549    44   133    1.317    48
1610612766 12014       759   278   680   3.260    53   170    2.444   150
           12015       572   194   476   2.446    55   158    2.066   129
           12016       642   225   589   2.675    42   179    1.535   150
           12017       508   189   431   2.188    48   146    1.615    82
           12018       571   198   426   2.335    66   166    2.007   109
           22014      8263  3089  7400  37.127   548  1719   28.061  1537
           22015      8574  3074  7018  36.795   892  2457   30.460  1534
           22016      8709  3137  7121  37.089   822  2368   28.922  1613
           22017      9088  3276  7272  38.326   829  2267   30.411  1707
           22018      9290  3382  7569  38.038   984  2838   29.386  1542
           22019       336   127   301   1.685    37   120    1.190    45
           42015       632   223   563   2.782    40   130    2.056   146

                       FTA  FT_PCT  OREB  DREB   REB   AST  STL  BLK   TOV  \
TEAM_ID    SEASON_ID
1610612737 12013       140   4.477    44   184   228   130   61   22   118
           12014       197   5.262    63   237   300   178   48   35   116
           12015       175   5.630    53   271   324   141   57   41   122
           12016       153   5.253    71   263   334   184   52   40   112
           12017       125   3.798    40   169   209   113   40   15    95
           12018       124   3.641    49   175   224   120   49   31   104
           22012       444  15.640   191   681   872   506  178   68   293
           22013      1799  64.601   731  2532  3263  2005  686  327  1220
           22014      1840  67.699   754  2728  3482  2171  786  396  1183
           22015      1716  66.851   715  2868  3583  2143  789  517  1265
           22016      2115  62.499   883  2902  3785  1985  721  424  1330
           22017      1737  66.456   775  2768  3543  1971  664  355  1274
           22018      2034  65.306  1015  3010  4025  2193  735  439  1451
           22019       112   3.768    47   135   182    70   48   32    83
           42012       157   3.990    50   180   230   115   44   23    72
           42013       174   5.837    64   211   275   118   46   32    90
           42014       311  12.387   157   542   699   381  136   79   194
           42015       205   7.895    89   354   443   226   75   76   137
           42016       174   4.552    68   198   266   134   36   20    93
1610612738 12013       188   6.358    93   227   320   168   77   38   126
           12014       203   6.010    80   260   340   184   84   27   145
           12015       116   3.190    62   195   257   122   43   33    85
           12016       168   5.219    63   239   302   160   69   31   120
           12017        89   2.834    44   147   191    93   40   21    54
           12018       103   3.083    43   151   194    76   34   26    51
           22012       369  12.983   126   515   641   367  124   85   244
           22013      1761  65.696  1012  2531  3543  1757  616  352  1226
           22014      1800  65.780   961  2806  3767  2097  727  309  1152
           22015      2093  69.404   996  2884  3880  2047  808  382  1157
           22016      2094  70.529   804  2840  3644  2118  668  364  1136
...                    ...     ...   ...   ...   ...   ...  ...  ...   ...
1610612764 42016       320  10.329   145   414   559   296  103   86   170
           42017       140   5.175    51   189   240   140   47   31    74
1610612765 12013       208   4.998    72   234   306   139   62   31   137
           12014       209   4.642    71   243   314   176   65   33   114
           12015       182   6.404    85   259   344   182   66   33   114
           12016       125   4.387    61   206   267   127   49   20    99
           12017        96   3.668    57   169   226   118   35   15    66
           12018       106   3.607    62   165   227   118   34   18    56
           22012       374  11.846   172   430   602   341  115   53   226
           22013      2175  56.387  1220  2558  3778  1730  724  399  1202
           22014      1973  61.526  1093  2764  3857  1847  661  394  1117
           22015      2097  56.381  1021  2791  3812  1592  580  319  1065
           22016      1631  59.981   912  2872  3784  1722  594  312   951
           22017      1673  62.992   858  2825  3683  1916  652  331  1092
           22018      1973  64.645   965  2856  3821  1884  601  342  1121
           22019        90   2.944    42   121   163    81   40   28    56
           42015        88   2.664    28   123   151    87   21   13    38
           42018        66   2.880    43   126   169    92   29   16    40
1610612766 12014       190   6.400    75   277   352   179   53   44   101
           12015       170   4.500    47   235   282   107   37   19    78
           12016       193   5.478    72   258   330   133   50   35   105
           12017       118   3.471    49   177   226    99   35   20    82
           12018       151   3.647    30   202   232   124   34   30    82
           22014      2064  66.348   904  2977  3881  1733  543  480  1019
           22015      1950  66.429   742  2934  3676  1807  610  448  1006
           22016      1984  68.453   762  2899  3661  1904  585  413   935
           22017      2280  63.732   856  2949  3805  1786  584  371  1046
           22018      1941  67.302   846  2860  3706  1949  622  411  1010
           22019        58   3.058    41   102   143    71   33   13    63
           42015       174   6.000    50   208   258    95   40   23    58

                        PF  PLUS_MINUS
TEAM_ID    SEASON_ID
1610612737 12013       112       -75.0
           12014       170        15.0
           12015       143        -5.0
           12016       154        41.0
           12017        91       -17.6
           12018       157       -18.0
           22012       367       -15.0
           22013      1610       -81.0
           22014      1577       433.0
           22015      1678       294.8
           22016      1579       -19.6
           22017      1668      -417.6
           22018      2039      -576.4
           22019       119        -0.8
           42012       145       -31.0
           42013       146        -7.0
           42014       315        -3.0
           42015       202       -10.0
           42016       128        -7.0
1610612738 12013       195        -6.0
           12014       174        53.0
           12015       119        34.0
           12016       163        41.0
           12017        85        39.0
           12018       121       -22.0
           22012       354       -34.0
           22013      1779      -336.0
           22014      1860         4.0
           22015      1902       318.6
           22016      1828       215.2
...                    ...         ...
1610612764 42016       299         0.0
           42017       126       -12.0
1610612765 12013       171       -18.0
           12014       168        32.0
           12015       166        54.0
           12016       117        27.0
           12017        93         1.0
           12018       119        -6.0
           22012       323      -132.0
           22013      1720      -289.0
           22014      1677       -82.0
           22015      1579        56.0
           22016      1479       -21.2
           22017      1568        22.0
           22018      1879       -39.6
           22019       106        24.6
           42015        76       -34.0
           42018        97       -95.0
1610612766 12014       197       -26.0
           12015       104        24.0
           12016       126       -51.0
           12017        93         3.0
           12018       129        24.0
           22014      1673      -271.0
           22015      1527       254.0
           22016      1394        30.0
           22017      1475        31.0
           22018      1597       -66.2
           22019        83        13.2
           42015       122       -62.0

[515 rows x 19 columns]

Notice that the newly created dataset has two levels of index, the "TEAM_ID" and "SEASON_ID"

#### If we want to convert these two indexes back as variables, we can use the "reset_index" command.

In [35]:
NBA_Team_Stats=NBA_Team_Stats.reset_index()
display(NBA_Team_Stats)

,TEAM_ID,SEASON_ID,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,1610612737,12013,523,193,459,2.520,34,131,1.576,103,...,4.477,44,184,228,130,61,22,118,112,-75.0
1,1610612737,12014,708,247,554,3.122,66,182,2.549,148,...,5.262,63,237,300,178,48,35,116,170,15.0
2,1610612737,12015,652,226,548,2.896,59,176,2.340,141,...,5.630,53,271,324,141,57,41,122,143,-5.0
3,1610612737,12016,686,261,593,3.083,50,159,2.140,114,...,5.253,71,263,334,184,52,40,112,154,41.0
4,1610612737,12017,480,167,410,2.045,51,156,1.611,95,...,3.798,40,169,209,113,40,15,95,91,-17.6
5,1610612737,12018,563,206,445,2.312,63,189,1.659,88,...,3.641,49,175,224,120,49,31,104,157,-18.0
6,1610612737,22012,2074,795,1701,9.824,155,454,7.206,329,...,15.640,191,681,872,506,178,68,293,367,-15.0
7,1610612737,22013,8272,3061,6719,37.846,747,2085,29.419,1403,...,64.601,731,2532,3263,2005,686,327,1220,1610,-81.0
8,1610612737,22014,8786,3253,7017,40.399,848,2256,32.719,1432,...,67.699,754,2728,3482,2171,786,396,1183,1577,433.0
9,1610612737,22015,8701,3265,7163,39.250,833,2403,29.818,1338,...,66.851,715,2868,3583,2143,789,517,1265,1678,294.8
10,1610612737,22016,8736,3219,7142,38.784,760,2214,29.491,1538,...,62.499,883,2902,3785,1985,721,424,1330,1579,-19.6
11,1610612737,22017,8683,3206,7208,37.909,919,2567,30.388,1352,...,66.456,775,2768,3543,1971,664,355,1274,1668,-417.6
12,1610612737,22018,9742,3555,7987,39.210,1121,3226,30.483,1511,...,65.306,1015,3010,4025,2193,735,439,1451,2039,-576.4
13,1610612737,22019,381,127,342,1.873,43,136,1.571,84,...,3.768,47,135,182,70,48,32,83,119,-0.8
14,1610612737,42012,536,196,464,2.533,37,112,1.900,107,...,3.990,50,180,230,115,44,23,72,145,-31.0
15,1610612737,42013,647,212,551,2.729,79,230,2.483,144,...,5.837,64,211,275,118,46,32,90,146,-7.0
16,1610612737,42014,1568,590,1369,6.907,145,458,5.030,243,...,12.387,157,542,699,381,136,79,194,315,-3.0
17,1610612737,42015,1001,366,848,4.337,106,318,3.332,163,...,7.895,89,354,443,226,75,76,137,202,-10.0
18,1610612737,42016,633,225,507,2.662,50,164,1.798,133,...,4.552,68,198,266,134,36,20,93,128,-7.0
19,1610612738,12013,754,276,654,3.404,54,186,2.313,148,...,6.358,93,227,320,168,77,38,126,195,-6.0
20,1610612738,12014,788,278,652,3.415,82,230,2.866,150,...,6.010,80,260,340,184,84,27,145,174,53.0
21,1610612738,12015,495,187,438,2.154,44,121,1.828,77,...,3.190,62,195,257,122,43,33,85,119,34.0
22,1610612738,12016,735,271,595,3.210,71,207,2.409,122,...,5.219,63,239,302,160,69,31,120,163,41.0
23,1610612738,12017,425,155,361,1.724,50,124,1.613,65,...,2.834,44,147,191,93,40,21,54,85,39.0
24,1610612738,12018,409,148,370,1.608,34,138,1.012,79,...,3.083,43,151,194,76,34,26,51,121,-22.0
25,1610612738,22012,1679,639,1327,8.192,119,316,6.483,282,...,12.983,126,515,641,367,124,85,244,354,-34.0
26,1610612738,22013,8044,3050,6991,36.818,580,1772,27.093,1364,...,65.696,1012,2531,3543,1757,616,352,1226,1779,-336.0
27,1610612738,22014,8728,3335,7580,38.363,701,2173,28.094,1357,...,65.780,961,2806,3767,2097,727,309,1152,1860,4.0
28,1610612738,22015,9124,3357,7697,38.360,762,2292,29.406,1648,...,69.404,996,2884,3880,2047,808,382,1157,1902,318.6
29,1610612738,22016,9319,3315,7330,39.823,1022,2844,31.486,1667,...,70.529,804,2840,3644,2118,668,364,1136,1828,215.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,1610612764,42016,1405,521,1139,5.959,109,344,4.170,254,...,10.329,145,414,559,296,103,86,170,299,0.0
486,1610612764,42017,643,238,511,2.793,48,131,2.239,119,...,5.175,51,189,240,140,47,31,74,126,-12.0
487,1610612765,12013,655,228,522,3.068,51,141,2.492,148,...,4.998,72,234,306,139,62,31,137,171,-18.0
488,1610612765,12014,698,249,570,3.067,59,171,2.399,141,...,4.642,71,243,314,176,65,33,114,168,32.0
489,1610612765,12015,824,302,667,3.641,78,212,2.940,142,...,6.404,85,259,344,182,66,33,114,166,54.0
490,1610612765,12016,565,216,485,2.680,40,129,1.804,93,...,4.387,61,206,267,127,49,20,99,117,27.0
491,1610612765,12017,517,202,437,2.311,43,119,1.796,70,...,3.668,57,169,226,118,35,15,66,93,1.0
492,1610612765,12018,524,190,467,2.042,67,204,1.628,77,...,3.607,62,165,227,118,34,18,56,119,-6.0
493,1610612765,22012,1534,585,1256,7.487,95,297,5.077,269,...,11.846,172,430,602,341,115,53,226,323,-132.0
494,1610612765,22013,8363,3194,7181,37.350,513,1625,25.813,1462,...,56.387,1220,2558,3778,1730,724,399,1202,1720,-289.0
495,1610612765,22014,8514,3187,7358,37.791,746,2163,29.631,1394,...,61.526,1093,2764,3857,1847,661,394,1117,1677,-82.0
496,1610612765,22015,8393,3121,7117,36.482,743,2150,28.588,1408,...,56.381,1021,2791,3812,1592,580,319,1065,1579,56.0
497,1610612765,22016,8351,3270,7298,37.161,638,1948,26.954,1173,...,59.981,912,2872,3784,1722,594,312,951,1479,-21.2
498,1610612765,22017,8754,3298,7310,38.371,913,2438,31.727,1245,...,62.992,858,2825,3683,1916,652,331,1092,1568,22.0
499,1610612765,22018,9020,3271,7500,37.520,1004,2946,29.104,1474,...,64.645,965,2856,3821,1884,601,342,1121,1879,-39.6
500,1610612765,22019,376,131,311,1.703,48,134,1.449,66,...,2.944,42,121,163,81,40,28,56,106,24.6
501,1610612765,42015,380,144,301,1.916,35,93,1.430,57,...,2.664,28,123,151,87,21,13,38,76,-34.0
502,1610612765,42018,392,150,387,1.549,44,133,1.317,48,...,2.880,43,126,169,92,29,16,40,97,-95.0
503,1610612766,12014,759,278,680,3.260,53,170,2.444,150,...,6.400,75,277,352,179,53,44,101,197,-26.0
504,1610612766,12015,572,194,476,2.446,55,158,2.066,129,...,4.500,47,235,282,107,37,19,78,104,24.0
505,1610612766,12016,642,225,589,2.675,42,179,1.535,150,...,5.478,72,258,330,133,50,35,105,126,-51.0
506,1610612766,12017,508,189,431,2.188,48,146,1.615,82,...,3.471,49,177,226,99,35,20,82,93,3.0
507,1610612766,12018,571,198,426,2.335,66,166,2.007,109,...,3.647,30,202,232,124,34,30,82,129,24.0
508,1610612766,22014,8263,3089,7400,37.127,548,1719,28.061,1537,...,66.348,904,2977,3881,1733,543,480,1019,1673,-271.0
509,1610612766,22015,8574,3074,7018,36.795,892,2457,30.460,1534,...,66.429,742,2934,3676,1807,610,448,1006,1527,254.0
510,1610612766,22016,8709,3137,7121,37.089,822,2368,28.922,1613,...,68.453,762,2899,3661,1904,585,413,935,1394,30.0
511,1610612766,22017,9088,3276,7272,38.326,829,2267,30.411,1707,...,63.732,856,2949,3805,1786,584,371,1046,1475,31.0
512,1610612766,22018,9290,3382,7569,38.038,984,2838,29.386,1542,...,67.302,846,2860,3706,1949,622,411,1010,1597,-66.2
513,1610612766,22019,336,127,301,1.685,37,120,1.190,45,...,3.058,41,102,143,71,33,13,63,83,13.2
514,1610612766,42015,632,223,563,2.782,40,130,2.056,146,...,6.000,50,208,258,95,40,23,58,122,-62.0

### We can create a variable that equals to the total number of observations within a specified group using the size() command.
- Create a variable that equals to the total number of games played by a team in each season, name this variable "GAME_COUNT".

In [36]:
NBA_Game_Count=NBA_Games.groupby(['TEAM_ID','SEASON_ID']).size().reset_index(name='GAME_COUNT')
display(NBA_Game_Count)

        TEAM_ID  SEASON_ID  GAME_COUNT
0    1610612737      12013           6
1    1610612737      12014           7
2    1610612737      12015           7
3    1610612737      12016           7
4    1610612737      12017           5
5    1610612737      12018           5
6    1610612737      22012          21
7    1610612737      22013          83
8    1610612737      22014          87
9    1610612737      22015          86
10   1610612737      22016          86
11   1610612737      22017          85
12   1610612737      22018          88
13   1610612737      22019           5
14   1610612737      42012           6
15   1610612737      42013           7
16   1610612737      42014          16
17   1610612737      42015          10
18   1610612737      42016           6
19   1610612738      12013           8
20   1610612738      12014           8
21   1610612738      12015           5
22   1610612738      12016           7
23   1610612738      12017           4
24   1610612738      12018           4
25   1610612738      22012          17
26   1610612738      22013          84
27   1610612738      22014          87
28   1610612738      22015          88
29   1610612738      22016          88
..          ...        ...         ...
485  1610612764      42016          13
486  1610612764      42017           6
487  1610612765      12013           7
488  1610612765      12014           7
489  1610612765      12015           8
490  1610612765      12016           6
491  1610612765      12017           5
492  1610612765      12018           5
493  1610612765      22012          16
494  1610612765      22013          84
495  1610612765      22014          87
496  1610612765      22015          83
497  1610612765      22016          83
498  1610612765      22017          85
499  1610612765      22018          86
500  1610612765      22019           4
501  1610612765      42015           4
502  1610612765      42018           4
503  1610612766      12014           8
504  1610612766      12015           6
505  1610612766      12016           7
506  1610612766      12017           5
507  1610612766      12018           5
508  1610612766      22014          89
509  1610612766      22015          84
510  1610612766      22016          84
511  1610612766      22017          85
512  1610612766      22018          85
513  1610612766      22019           4
514  1610612766      42015           7

[515 rows x 3 columns]

## Saving data

### We can save a dataframe by exporting the edited dataframe to csv file using the “to_csv” command.
- Save merged data as a csv file 
_We can use the "index=False" command to save the data without adding the index as a column in the csv file_

In [ ]:
NBA_Games.to_csv("../../Data/Week 2/NBA_Games.csv", index=False)